wget -O 1.html https://valen.com/blog 
wget -O 2.html https://valen.com/blog/page/2/ 
wget -O 3.html https://valen.com/blog/page/3/ 
wget -O 4.html https://valen.com/blog/page/4/ 
wget -O 5.html https://valen.com/blog/page/5/ 
wget -O 6.html https://valen.com/blog/page/6/ 
wget -O 7.html https://valen.com/blog/page/7/ 
wget -O 8.html https://valen.com/blog/page/8/ 
wget -O 9.html https://valen.com/blog/page/9/ 
wget -O 10.html https://valen.com/blog/page/10/ 
wget -O 11.html https://valen.com/blog/page/11/ 
