wget -O the-intensifying-impacts-of-the-innovation-economy.html https://valen.com/2019/05/20/the-intensifying-impacts-of-the-innovation-economy/
wget -O optimize-your-insurance-engine-with-data-consortiums.html https://valen.com/2019/03/20/optimize-your-insurance-engine-with-data-consortiums/
wget -O 3-detours-taking-your-data-strategy-off-track.html https://valen.com/2018/11/12/3-detours-taking-your-data-strategy-off-track/
wget -O the-nature-of-risk-is-changing-what-does-that-mean-for-leadership.html https://valen.com/2018/10/18/the-nature-of-risk-is-changing-what-does-that-mean-for-leadership/
wget -O data-is-insurances-ultimate-equalizer.html https://valen.com/2018/09/07/data-is-insurances-ultimate-equalizer/
wget -O changing-nature-of-risk-what-does-it-mean-for-leadership.html https://valen.com/2018/08/03/changing-nature-of-risk-what-does-it-mean-for-leadership/
wget -O whats-your-analytics-story.html https://valen.com/2018/05/31/whats-your-analytics-story/
wget -O commercial-autos-wild-ride-continues.html https://valen.com/2018/04/20/commercial-autos-wild-ride-continues/
wget -O little-things-olympians-can-teach-executives.html https://valen.com/2018/02/14/little-things-olympians-can-teach-executives/
wget -O secret-ingredient-highly-innovative-teams-change-game.html https://valen.com/2018/02/13/secret-ingredient-highly-innovative-teams-change-game/
wget -O first-conference-features-innovators-winter-fun-vail.html https://valen.com/2013/10/02/first-conference-features-innovators-winter-fun-vail/
wget -O real-momentum-building-data-analytics-property-casualty.html https://valen.com/2013/09/24/real-momentum-building-data-analytics-property-casualty/
wget -O valens-2014-outlook-commercial-lines.html https://valen.com/2013/09/18/valens-2014-outlook-commercial-lines/
wget -O underwriter-future.html https://valen.com/2013/09/10/underwriter-future/
wget -O predictive-analytics-helps-insurance-agents-customers.html https://valen.com/2013/08/20/predictive-analytics-helps-insurance-agents-customers/
wget -O 5-top-challenges-carriers-face-rapidly-changing-industry.html https://valen.com/2013/08/13/5-top-challenges-carriers-face-rapidly-changing-industry/
wget -O misclassified-payroll-matters-tune-76-8-billion.html https://valen.com/2013/07/16/misclassified-payroll-matters-tune-76-8-billion/
wget -O tackling-underwriting-profitability-head.html https://valen.com/2013/07/09/tackling-underwriting-profitability-head/
wget -O what-makes-underwriter-adoption-of-predictive-analytics-challenging.html https://valen.com/2013/06/06/what-makes-underwriter-adoption-of-predictive-analytics-challenging/
wget -O change-doesnt-have-to-be-painful.html https://valen.com/2013/05/21/change-doesnt-have-to-be-painful/
wget -O it-is-all-about-price.html https://valen.com/2013/05/14/it-is-all-about-price/
wget -O you-need-more-visibility.html https://valen.com/2013/05/07/you-need-more-visibility/
wget -O welcome-to-this-week-in-analytics.html https://valen.com/2013/04/30/welcome-to-this-week-in-analytics/
wget -O goosebump-moments-career.html https://valen.com/2018/02/07/goosebump-moments-career/
wget -O market-share-consolidation-moves-quickly.html https://valen.com/2018/01/16/market-share-consolidation-moves-quickly/
wget -O clock-strikes-midnight.html https://valen.com/2017/12/29/clock-strikes-midnight/
wget -O beauty-model-maintenance-told-davinci.html https://valen.com/2017/12/12/beauty-model-maintenance-told-davinci/
wget -O four-things-im-thankful.html https://valen.com/2017/11/21/four-things-im-thankful/
wget -O 3-takeaways-insuretech-connect.html https://valen.com/2017/11/07/3-takeaways-insuretech-connect/
wget -O back-basics-predictive-analytics-reducing-loss-ratio.html https://valen.com/2017/10/25/back-basics-predictive-analytics-reducing-loss-ratio/
wget -O race-bottom-myth.html https://valen.com/2017/10/10/race-bottom-myth/
wget -O pursuing-better-rating-predictive-analytics-can-help.html https://valen.com/2017/09/12/pursuing-better-rating-predictive-analytics-can-help/
wget -O the-magic-bullet.html https://valen.com/2017/08/24/the-magic-bullet/
wget -O two-critical-concerns-work-comp-insurers.html https://valen.com/2017/08/09/two-critical-concerns-work-comp-insurers/
wget -O the-power-of-the-underwriter.html https://valen.com/2017/07/25/the-power-of-the-underwriter/
wget -O 5-must-dos-data-collection.html https://valen.com/2017/07/12/5-must-dos-data-collection/
wget -O commercial-autos-wild-ride.html https://valen.com/2017/06/21/commercial-autos-wild-ride/
wget -O meet-bob-claims-superhero.html https://valen.com/2017/05/11/meet-bob-claims-superhero/
wget -O market-leaving-behind-valens-roi-study-showcases-insurers-leading-work-comp.html https://valen.com/2017/05/09/market-leaving-behind-valens-roi-study-showcases-insurers-leading-work-comp/
wget -O davids-data-analytics-slingshot.html https://valen.com/2017/04/18/davids-data-analytics-slingshot/
wget -O insurtech-disruption-end-distribution.html https://valen.com/2017/03/21/insurtech-disruption-end-distribution/
wget -O sometimes-you-have-to-say-no-to-the-data.html https://valen.com/2017/03/06/sometimes-you-have-to-say-no-to-the-data/
wget -O distraction-danger.html https://valen.com/2017/02/14/distraction-danger/
wget -O industry-talent-crisis.html https://valen.com/2017/02/02/industry-talent-crisis/
wget -O 3-insurance-industry-lessons-2016.html https://valen.com/2017/01/17/3-insurance-industry-lessons-2016/
wget -O insuretech-adaptation-not-just-disruption.html https://valen.com/2016/12/20/insuretech-adaptation-not-just-disruption/
wget -O 3-reasons-insurers-lack-strong-pricing-helps-thrive.html https://valen.com/2016/11/03/3-reasons-insurers-lack-strong-pricing-helps-thrive/
wget -O half-work-comp-policies-include-payroll-errors.html https://valen.com/2016/07/26/half-work-comp-policies-include-payroll-errors/
wget -O valen-analytics-2016-scholarship-award-winner.html https://valen.com/2016/07/06/valen-analytics-2016-scholarship-award-winner/
wget -O insurance-consumers-want-innovation.html https://valen.com/2016/06/01/insurance-consumers-want-innovation/
wget -O best-time-implement-insurance-predictive-model.html https://valen.com/2016/05/17/best-time-implement-insurance-predictive-model/
wget -O will-predictive-analytics-replace-underwriters.html https://valen.com/2016/05/03/will-predictive-analytics-replace-underwriters/
wget -O innovators-dilemma-a-constant-across-every-industry-even-insurance.html https://valen.com/2016/04/12/innovators-dilemma-a-constant-across-every-industry-even-insurance/
wget -O severe-implications-of-payroll-misclassification-premium-fraud.html https://valen.com/2016/02/23/severe-implications-of-payroll-misclassification-premium-fraud/
wget -O the-perfect-pair-human-judgement-and-analytics.html https://valen.com/2016/02/10/the-perfect-pair-human-judgement-and-analytics/
wget -O what-really-drives-insurance-market-cycles.html https://valen.com/2016/01/06/what-really-drives-insurance-market-cycles/
wget -O the-angst-of-an-insurance-industry-outlook-report.html https://valen.com/2015/12/28/the-angst-of-an-insurance-industry-outlook-report/
wget -O planning-for-a-predictive-analytics-implementation.html https://valen.com/2015/11/30/planning-for-a-predictive-analytics-implementation/
wget -O how-to-gain-organizational-buy-in-of-predictive-analytics.html https://valen.com/2015/11/03/how-to-gain-organizational-buy-in-of-predictive-analytics/
wget -O 1st-step-in-a-predictive-analytics-implementation.html https://valen.com/2015/10/13/1st-step-in-a-predictive-analytics-implementation/
wget -O roadblocks-to-insurance-innovation.html https://valen.com/2015/09/16/roadblocks-to-insurance-innovation/
wget -O insurance-carriers-race-for-the-top-10-of-business.html https://valen.com/2015/09/01/insurance-carriers-race-for-the-top-10-of-business/
wget -O is-insurance-an-easy-target-for-criticism.html https://valen.com/2015/08/11/is-insurance-an-easy-target-for-criticism/
wget -O actuaries-vs-underwriters-who-wins.html https://valen.com/2015/07/28/actuaries-vs-underwriters-who-wins/
wget -O loss-ratio-suffers-in-insurance-if-you-do-this-wrong.html https://valen.com/2015/07/14/loss-ratio-suffers-in-insurance-if-you-do-this-wrong/
wget -O bringing-insurance-into-the-21st-century.html https://valen.com/2015/06/23/bringing-insurance-into-the-21st-century/
wget -O predictive-analytics-implementation-steps.html https://valen.com/2015/06/02/predictive-analytics-implementation-steps/
wget -O how-predictive-analytics-combats-adverse-selection.html https://valen.com/2015/05/12/how-predictive-analytics-combats-adverse-selection/
wget -O the-future-of-the-insurance-industry-is-now.html https://valen.com/2015/04/29/the-future-of-the-insurance-industry-is-now/
wget -O predictive-analytics-is-not-a-magic-bullet.html https://valen.com/2015/04/14/predictive-analytics-is-not-a-magic-bullet/
wget -O how-to-raise-a-predictive-model-you-can-live-with.html https://valen.com/2015/03/24/how-to-raise-a-predictive-model-you-can-live-with/
wget -O implementing-predictive-analytics-youre-wrong.html https://valen.com/2015/02/10/implementing-predictive-analytics-youre-wrong/
wget -O two-predictive-statistics-you-need-to-evaluate-your-model.html https://valen.com/2015/01/28/two-predictive-statistics-you-need-to-evaluate-your-model/
wget -O 3-lessons-insurance-customers-taught-us.html https://valen.com/2015/01/26/3-lessons-insurance-customers-taught-us/
wget -O big-data-in-insurance-a-glimpse-into-2015.html https://valen.com/2015/01/13/big-data-in-insurance-a-glimpse-into-2015/
wget -O insurance-industry-most-exciting-in-2015.html https://valen.com/2015/01/06/insurance-industry-most-exciting-in-2015/
wget -O insurance-data-analytics-christmas-carol.html https://valen.com/2014/12/22/insurance-data-analytics-christmas-carol/
wget -O a-farewell-letter-to-traditional-insurance-loss-ratio.html https://valen.com/2014/12/09/a-farewell-letter-to-traditional-insurance-loss-ratio/
wget -O predictive-analytics-giving-thanks-in-2014.html https://valen.com/2014/11/25/predictive-analytics-giving-thanks-in-2014/
wget -O top-6-myths-about-predictive-modeling-and-analytics.html https://valen.com/2014/11/19/top-6-myths-about-predictive-modeling-and-analytics/
wget -O insurance-data-and-analytics-revolution.html https://valen.com/2014/11/11/insurance-data-and-analytics-revolution/
wget -O valen-summit-2015-announced-gold-rush.html https://valen.com/2014/10/24/valen-summit-2015-announced-gold-rush/
wget -O workers-compensation-underwriting-for-baldwin-lyons.html https://valen.com/2014/07/23/workers-compensation-underwriting-for-baldwin-lyons/
wget -O risk-score-big-news-for-insurance-industry.html https://valen.com/2014/07/17/risk-score-big-news-for-insurance-industry/
wget -O how-to-grow-profitably-and-avoid-adverse-selection.html https://valen.com/2014/07/09/how-to-grow-profitably-and-avoid-adverse-selection/
wget -O identify-loss-ratio-difference-between-loss-free-workers-compensation-policies.html https://valen.com/2014/07/07/identify-loss-ratio-difference-between-loss-free-workers-compensation-policies/
wget -O how-predictive-analytics-helps-insurance-company-competitors.html https://valen.com/2014/06/24/how-predictive-analytics-helps-insurance-company-competitors/
wget -O farm-bureau-financial-services-analytics-implementation.html https://valen.com/2014/06/23/farm-bureau-financial-services-analytics-implementation/
wget -O pricing-insurance-policies.html https://valen.com/2014/06/09/pricing-insurance-policies/
wget -O insurer-eulogy-adverse-selection.html https://valen.com/2014/05/28/insurer-eulogy-adverse-selection/
wget -O valen-recognized-vice-president-joe-biden-stem-education.html https://valen.com/2014/05/27/valen-recognized-vice-president-joe-biden-stem-education/
wget -O meet-tomorrows-talent-challenge-2014-scholarship-recipient.html https://valen.com/2014/05/08/meet-tomorrows-talent-challenge-2014-scholarship-recipient/
wget -O 1-thing-carriers-forget-preventing-fraud-can-save-millions.html https://valen.com/2014/05/05/1-thing-carriers-forget-preventing-fraud-can-save-millions/
wget -O 500m-work-comp-fraud-new-york-tip-iceberg.html https://valen.com/2014/04/27/500m-work-comp-fraud-new-york-tip-iceberg/
wget -O valen-promotes-insurance-careers-nations-top-business-leaders.html https://valen.com/2014/04/21/valen-promotes-insurance-careers-nations-top-business-leaders/
wget -O 1-secret-success-advanced-analytics.html https://valen.com/2014/03/03/1-secret-success-advanced-analytics/
wget -O guest-post-todays-small-commercial-automation-enough.html https://valen.com/2014/02/11/guest-post-todays-small-commercial-automation-enough/
wget -O 2014-outlook-personal-lines.html https://valen.com/2014/01/16/2014-outlook-personal-lines/
wget -O 550-commercial-underwriters-cant-wrong.html https://valen.com/2013/12/19/550-commercial-underwriters-cant-wrong/
wget -O valen-welcomes-fhm-new-customer.html https://valen.com/2013/11/19/valen-welcomes-fhm-new-customer/
wget -O will-best-talent-choose-insurance.html https://valen.com/2013/11/05/will-best-talent-choose-insurance/
wget -O coolest-thing-weve-announced.html https://valen.com/2013/10/17/coolest-thing-weve-announced/
wget -O valens-new-product-helps-homeowners-carriers-chart-course-profitability.html https://valen.com/2013/10/09/valens-new-product-helps-homeowners-carriers-chart-course-profitability/
